"""empty message

Revision ID: 149061cf5298
Revises: 27ec660bdebb
Create Date: 2024-03-25 10:05:50.880889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149061cf5298'
down_revision = '27ec660bdebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loads_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loads_table', schema=None) as batch_op:
        batch_op.drop_column('pickup')

    # ### end Alembic commands ###
