"""empty message

Revision ID: 27ec660bdebb
Revises: 
Create Date: 2024-03-19 16:16:41.965005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ec660bdebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('truckers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('trailer', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loads_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dropoff', sa.String(), nullable=True),
    sa.Column('materials', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('payout', sa.String(), nullable=True),
    sa.Column('trucker_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_loads_table_company_id_companies_table')),
    sa.ForeignKeyConstraint(['trucker_id'], ['truckers_table.id'], name=op.f('fk_loads_table_trucker_id_truckers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loads_table')
    op.drop_table('truckers_table')
    op.drop_table('companies_table')
    # ### end Alembic commands ###
