"""empty message

Revision ID: 28e92b40d720
Revises: 149061cf5298
Create Date: 2024-03-26 11:55:41.487710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e92b40d720'
down_revision = '149061cf5298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trucker_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_connect_table_company_id_companies_table')),
    sa.ForeignKeyConstraint(['trucker_id'], ['truckers_table.id'], name=op.f('fk_connect_table_trucker_id_truckers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connect_table')
    # ### end Alembic commands ###
