"""empty message

Revision ID: c363d844b256
Revises: dd02236b0308
Create Date: 2024-03-19 15:36:46.822571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c363d844b256'
down_revision = 'dd02236b0308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truckers_table', schema=None) as batch_op:
        batch_op.alter_column('trailer',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truckers_table', schema=None) as batch_op:
        batch_op.alter_column('trailer',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
